#!/usr/bin/env python3
"""
Brain Bridge: Hub penghubung antara Global Brain (~/.ai-station/brain)
dengan berbagai CLI (Antigravity CLI, Qoder CLI, Open Interpreter, dsb.)
"""

import os
import sys
import json
import yaml
from pathlib import Path

AI_STATION_DIR = Path.home() / ".ai-station"
BRAIN_DIR = AI_STATION_DIR / "brain"
CONFIG_FILE = AI_STATION_DIR / "config" / "slots.yaml"
WORKSPACES_DIR = BRAIN_DIR / "workspaces"


def print_banner():
    print("=" * 60)
    print(" 🧠 AI WORKSTATION CORE - UNIVERSAL BRAIN BRIDGE")
    print(f" Brain Location: {BRAIN_DIR}")
    print("=" * 60)


def link_workspace(target_path: Path):
    target_path = target_path.resolve()
    if not target_path.exists():
        print(f"[-] Error: Target directory '{target_path}' tidak ditemukan.")
        return False

    print(f"[*] Menghubungkan project ke Global Brain: {target_path}")

    # 1. Update symlink current_project
    current_link = WORKSPACES_DIR / "current_project"
    if current_link.is_symlink() or current_link.exists():
        current_link.unlink()
    current_link.symlink_to(target_path)
    print(f"    [+] Updated symlink: {current_link} -> {target_path}")

    # 2. Inject context file untuk berbagai CLI (Antigravity, Qoder, universal agent)
    # File AGENT_BRAIN.md sebagai master reference
    agent_brain_doc = target_path / ".ai_brain_link.md"
    agent_brain_doc.write_text(
        f"""<!-- AUTO-GENERATED BY AI WORKSTATION BRAIN BRIDGE -->
# Global Brain Context Pointer
Project ini terhubung ke AI Workstation Brain di: `{BRAIN_DIR}`.
- Global Identity: `{BRAIN_DIR / 'IDENTITY.md'}`
- Global Rules: `{BRAIN_DIR / 'rules'}`
- Shared Skills: `{BRAIN_DIR / 'skills'}`
- Memory & Facts: `{BRAIN_DIR / 'memory' / 'global_facts.jsonl'}`
"""
    )
    print(f"    [+] Created context pointer: {agent_brain_doc.name}")

    # 3. Setup folder bridge untuk Qoder jika diperlukan (.qoder/rules)
    qoder_rules = target_path / ".qoder" / "rules"
    qoder_rules.mkdir(parents=True, exist_ok=True)
    qoder_link = qoder_rules / "global_rules.md"
    if not qoder_link.exists() and not qoder_link.is_symlink():
        try:
            qoder_link.symlink_to(BRAIN_DIR / "rules" / "coding_standards.md")
            print(f"    [+] Linked Qoder rules: {qoder_link.name}")
        except Exception:
            pass

    print("[✓] Workspace berhasil terhubung dengan Global Brain!")
    return True


def show_status():
    print_banner()
    skills = [s for s in (BRAIN_DIR / "skills").rglob("*.md") if s.name != "SKILLS.md"]
    rules = list((BRAIN_DIR / "rules").glob("*.md"))
    memories = [m for m in (BRAIN_DIR / "memory").rglob("*.md") if m.name != "MEMORY.md"]
    facts_file = BRAIN_DIR / "memory" / "global_facts.jsonl"
    fact_count = 0
    if facts_file.exists():
        with open(facts_file) as f:
            fact_count = sum(1 for _ in f if _.strip())

    current_link = WORKSPACES_DIR / "current_project"
    curr_ws = current_link.resolve() if current_link.exists() else "None (Belum dihubungkan)"

    print(f"[*] Active Workspace   : {curr_ws}")
    print(f"[*] Categorized Skills : {len(skills)} skills in catalog (visual, coding, sysadmin, analysis, learned)")
    print(f"[*] Active Rules       : {len(rules)} global rules")
    print(f"[*] Persistent Memories: {len(memories)} categorized documents + {fact_count} facts")

    if CONFIG_FILE.exists():
        with open(CONFIG_FILE) as f:
            conf = yaml.safe_load(f)
            print(f"[*] Active Team Slot   : {conf.get('active_team')}")
            print(f"[*] Available Teams    : {len(conf.get('teams', []))} teams")
            for t in conf.get('teams', []):
                print(f"    - {t['name']} (ID: {t['id']})")
    print("=" * 60)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == "link":
            path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path.cwd()
            link_workspace(path)
        elif cmd == "status":
            show_status()
        else:
            print("Usage: brain_bridge.py [status | link <optional_path>]")
    else:
        show_status()
